version: "3.8"
services:
  server:
    image: vlabra228/mafia-server
    ports:
      - "50051:50051/tcp"
    hostname: localhost
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: localhost
    ports:
        - 15672:15672
        - 5672:5672
    expose:
    - 15672
    - 5672


